# fly.toml app configuration file generated for dnd-be-bold-water-9324 on 2023-12-31T19:13:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dnd-be-bold-water-9324"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
